#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Commissioner Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

BUILD_DIR=${BUILD_DIR:-./build}
SRC_ROOT=$(cd "$(dirname $0)"/..; pwd)

code_make()
{
    [ -d ./extlibs ] || git submodule update --init
    echo "code_make(): $BUILD_DIR $@"
    case "$1" in
        all|clean)
            TARGET="--target $1"
            shift
            ;;
        *)
            ;;
    esac
    
    cmake --build $BUILD_DIR $TARGET $@
}

case "$1" in
    -h|--help|help)
        echo "Usage: $0 [help|clean|all]"
        echo "  - clean          : the parameter to be passed to cmake as --target clean"
        echo "  - all            : the parameter to be passed to cmake as --target all"
        echo ""
        echo "  Any other parameters will be directly passed to cmake."
        echo "  Examples:"
        echo ""
        echo "  $0 clean"
        echo "  $0 all --clean-first"
        echo ""
        ;;
    clean)
        code_make $@
        ;;
    all)
        code_make $@
        ;;
    *)
        code_make $@

esac

