#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Commissioner Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

BUILD_DIR=${BUILD_DIR:-./build}

build_type=${1:-"-d"}
# echo "build_type = $build_type"
if [ $build_type = "-d" ] || [ $build_type = "--debug" ]; then
    [ -n "$1" ] && shift
    BUILD_OPT=-DCMAKE_BUILD_TYPE=Debug
    echo "Configure for debugging..."
fi

if [ $build_type = "-r" ] || [ $build_type = "--release" ]; then
    shift
    BUILD_OPT=-DCMAKE_BUILD_TYPE=Release
    echo "Configure for releasing..."
fi

echo $BUILD_OPT

TARGET=$1
TARGET=${TARGET:-all}

# suppress cmake warning
# currently it is -Wno-dev
NO_WARN=${NO_WARN:--Wno-dev}

remake_dir()
{
    echo remaking $(pwd)
    [ -d $BUILD_DIR ] || mkdir $BUILD_DIR
    rm -fR $BUILD_DIR/*
    cd $BUILD_DIR
    cmake $NO_WARN $BUILD_OPT ..
    cd -
}

print_help()
{
    echo "Usage: $0 [-d|--debug|-r|--release] [help]"
    echo ""
}

case "$TARGET" in
    help)
        print_help
        ;;
    *)
        remake_dir
        ;;
esac
