#!/bin/bash

BUILD_DIR=${BUILD_DIR:-./build}

build_type=${1:-"-d"}
# echo "build_type = $build_type"
if [ $build_type = "-d" ] || [ $build_type = "--debug" ];
then
    [ -n "$1" ] && shift
    BUILD_OPT=-DCMAKE_BUILD_TYPE=Debug
    echo "Configure for debugging..."
fi

if [ $build_type = "-r" ] || [ $build_type = "--release" ];
then
    shift
    BUILD_OPT=-DCMAKE_BUILD_TYPE=Release
    echo "Configure for releasing..."
fi

echo $BUILD_OPT

TARGET=$1
TARGET=${TARGET:-all}

# suppress cmake warning
# currently it is -Wno-dev
NO_WARN=${NO_WARN:--Wno-dev}

remake_dir()
{
    echo remaking `pwd`
    [ -d $BUILD_DIR ] || mkdir $BUILD_DIR
    rm -fR $BUILD_DIR/*
    cd $BUILD_DIR
    cmake $NO_WARN $BUILD_OPT ..
    cd -
}

print_help()
{
    echo "Usage: $0 [-d|--debug|-r|--release] [help]"
    echo ""
}

case "$TARGET" in
    help)
        print_help
        ;;
    *)
        remake_dir
        ;;
esac

